/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefaultLayoutRouteImport } from './routes/_defaultLayout'
import { Route as DefaultLayoutIndexRouteImport } from './routes/_defaultLayout/index'
import { Route as ToolsSoopupRouteImport } from './routes/tools/soopup'
import { Route as ApiCafeArticlesRouteImport } from './routes/api/cafe-articles'
import { Route as DefaultLayoutSoopRouteImport } from './routes/_defaultLayout/soop'
import { Route as DefaultLayoutReviewRouteImport } from './routes/_defaultLayout/review'
import { Route as DefaultLayoutLiveRouteImport } from './routes/_defaultLayout/live'
import { Route as DefaultLayoutCalendarRouteImport } from './routes/_defaultLayout/calendar'
import { Route as DefaultLayoutCafeRouteImport } from './routes/_defaultLayout/cafe'

const DefaultLayoutRoute = DefaultLayoutRouteImport.update({
  id: '/_defaultLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutIndexRoute = DefaultLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const ToolsSoopupRoute = ToolsSoopupRouteImport.update({
  id: '/tools/soopup',
  path: '/tools/soopup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCafeArticlesRoute = ApiCafeArticlesRouteImport.update({
  id: '/api/cafe-articles',
  path: '/api/cafe-articles',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutSoopRoute = DefaultLayoutSoopRouteImport.update({
  id: '/soop',
  path: '/soop',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutReviewRoute = DefaultLayoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutLiveRoute = DefaultLayoutLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutCalendarRoute = DefaultLayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutCafeRoute = DefaultLayoutCafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => DefaultLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultLayoutIndexRoute
  '/cafe': typeof DefaultLayoutCafeRoute
  '/calendar': typeof DefaultLayoutCalendarRoute
  '/live': typeof DefaultLayoutLiveRoute
  '/review': typeof DefaultLayoutReviewRoute
  '/soop': typeof DefaultLayoutSoopRoute
  '/api/cafe-articles': typeof ApiCafeArticlesRoute
  '/tools/soopup': typeof ToolsSoopupRoute
}
export interface FileRoutesByTo {
  '/cafe': typeof DefaultLayoutCafeRoute
  '/calendar': typeof DefaultLayoutCalendarRoute
  '/live': typeof DefaultLayoutLiveRoute
  '/review': typeof DefaultLayoutReviewRoute
  '/soop': typeof DefaultLayoutSoopRoute
  '/api/cafe-articles': typeof ApiCafeArticlesRoute
  '/tools/soopup': typeof ToolsSoopupRoute
  '/': typeof DefaultLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_defaultLayout': typeof DefaultLayoutRouteWithChildren
  '/_defaultLayout/cafe': typeof DefaultLayoutCafeRoute
  '/_defaultLayout/calendar': typeof DefaultLayoutCalendarRoute
  '/_defaultLayout/live': typeof DefaultLayoutLiveRoute
  '/_defaultLayout/review': typeof DefaultLayoutReviewRoute
  '/_defaultLayout/soop': typeof DefaultLayoutSoopRoute
  '/api/cafe-articles': typeof ApiCafeArticlesRoute
  '/tools/soopup': typeof ToolsSoopupRoute
  '/_defaultLayout/': typeof DefaultLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cafe'
    | '/calendar'
    | '/live'
    | '/review'
    | '/soop'
    | '/api/cafe-articles'
    | '/tools/soopup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cafe'
    | '/calendar'
    | '/live'
    | '/review'
    | '/soop'
    | '/api/cafe-articles'
    | '/tools/soopup'
    | '/'
  id:
    | '__root__'
    | '/_defaultLayout'
    | '/_defaultLayout/cafe'
    | '/_defaultLayout/calendar'
    | '/_defaultLayout/live'
    | '/_defaultLayout/review'
    | '/_defaultLayout/soop'
    | '/api/cafe-articles'
    | '/tools/soopup'
    | '/_defaultLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DefaultLayoutRoute: typeof DefaultLayoutRouteWithChildren
  ApiCafeArticlesRoute: typeof ApiCafeArticlesRoute
  ToolsSoopupRoute: typeof ToolsSoopupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_defaultLayout': {
      id: '/_defaultLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_defaultLayout/': {
      id: '/_defaultLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutIndexRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/tools/soopup': {
      id: '/tools/soopup'
      path: '/tools/soopup'
      fullPath: '/tools/soopup'
      preLoaderRoute: typeof ToolsSoopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cafe-articles': {
      id: '/api/cafe-articles'
      path: '/api/cafe-articles'
      fullPath: '/api/cafe-articles'
      preLoaderRoute: typeof ApiCafeArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_defaultLayout/soop': {
      id: '/_defaultLayout/soop'
      path: '/soop'
      fullPath: '/soop'
      preLoaderRoute: typeof DefaultLayoutSoopRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/review': {
      id: '/_defaultLayout/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof DefaultLayoutReviewRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/live': {
      id: '/_defaultLayout/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof DefaultLayoutLiveRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/calendar': {
      id: '/_defaultLayout/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof DefaultLayoutCalendarRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/cafe': {
      id: '/_defaultLayout/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof DefaultLayoutCafeRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
  }
}

interface DefaultLayoutRouteChildren {
  DefaultLayoutCafeRoute: typeof DefaultLayoutCafeRoute
  DefaultLayoutCalendarRoute: typeof DefaultLayoutCalendarRoute
  DefaultLayoutLiveRoute: typeof DefaultLayoutLiveRoute
  DefaultLayoutReviewRoute: typeof DefaultLayoutReviewRoute
  DefaultLayoutSoopRoute: typeof DefaultLayoutSoopRoute
  DefaultLayoutIndexRoute: typeof DefaultLayoutIndexRoute
}

const DefaultLayoutRouteChildren: DefaultLayoutRouteChildren = {
  DefaultLayoutCafeRoute: DefaultLayoutCafeRoute,
  DefaultLayoutCalendarRoute: DefaultLayoutCalendarRoute,
  DefaultLayoutLiveRoute: DefaultLayoutLiveRoute,
  DefaultLayoutReviewRoute: DefaultLayoutReviewRoute,
  DefaultLayoutSoopRoute: DefaultLayoutSoopRoute,
  DefaultLayoutIndexRoute: DefaultLayoutIndexRoute,
}

const DefaultLayoutRouteWithChildren = DefaultLayoutRoute._addFileChildren(
  DefaultLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DefaultLayoutRoute: DefaultLayoutRouteWithChildren,
  ApiCafeArticlesRoute: ApiCafeArticlesRoute,
  ToolsSoopupRoute: ToolsSoopupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
