/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DefaultLayoutRouteImport } from './routes/_defaultLayout'
import { Route as BluejumpNewsDotxmlRouteImport } from './routes/bluejump-news[.]xml'
import { Route as DefaultLayoutIndexRouteImport } from './routes/_defaultLayout/index'
import { Route as DefaultLayoutCafeRouteImport } from './routes/_defaultLayout/cafe'
import { Route as DefaultLayoutCalendarRouteImport } from './routes/_defaultLayout/calendar'
import { Route as DefaultLayoutClipperRouteImport } from './routes/_defaultLayout/clipper'
import { Route as DefaultLayoutLiveRouteImport } from './routes/_defaultLayout/live'
import { Route as DefaultLayoutMusicbookRouteImport } from './routes/_defaultLayout/musicbook'
import { Route as DefaultLayoutSoopRouteImport } from './routes/_defaultLayout/soop'
import { Route as DefaultLayoutVodRouteImport } from './routes/_defaultLayout/vod'
import { Route as ApiCafeArticlesRouteImport } from './routes/api/cafe-articles'
import { Route as ToolsSoopcommentRouteImport } from './routes/tools/soopcomment'
import { Route as ToolsSoopupRouteImport } from './routes/tools/soopup'
import { Route as DefaultLayoutMusicbookIndexRouteImport } from './routes/_defaultLayout/musicbook/index'
import { Route as DefaultLayoutMusicbook9mogu9RouteImport } from './routes/_defaultLayout/musicbook/9mogu9'
import { Route as DefaultLayoutMusicbookHarohaRouteImport } from './routes/_defaultLayout/musicbook/haroha'
import { Route as DefaultLayoutMusicbookMarronieRouteImport } from './routes/_defaultLayout/musicbook/marronie'
import { Route as DefaultLayoutMusicbookOverlapRouteImport } from './routes/_defaultLayout/musicbook/overlap'
import { Route as DefaultLayoutMusicbookYangdokiRouteImport } from './routes/_defaultLayout/musicbook/yangdoki'
import { Route as ToolsSoopthumbnailIndexRouteImport } from './routes/tools/soopthumbnail/index'
import { Route as ToolsSoopthumbnail9mogu9RouteImport } from './routes/tools/soopthumbnail/9mogu9'
import { Route as ToolsSoopthumbnailDlsn9911RouteImport } from './routes/tools/soopthumbnail/dlsn9911'
import { Route as ToolsSoopthumbnailHarohaRouteImport } from './routes/tools/soopthumbnail/haroha'

const DefaultLayoutRoute = DefaultLayoutRouteImport.update({
  id: '/_defaultLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const BluejumpNewsDotxmlRoute = BluejumpNewsDotxmlRouteImport.update({
  id: '/bluejump-news.xml',
  path: '/bluejump-news.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutIndexRoute = DefaultLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutCafeRoute = DefaultLayoutCafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutCalendarRoute = DefaultLayoutCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutClipperRoute = DefaultLayoutClipperRouteImport.update({
  id: '/clipper',
  path: '/clipper',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutLiveRoute = DefaultLayoutLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutMusicbookRoute = DefaultLayoutMusicbookRouteImport.update({
  id: '/musicbook',
  path: '/musicbook',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutSoopRoute = DefaultLayoutSoopRouteImport.update({
  id: '/soop',
  path: '/soop',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const DefaultLayoutVodRoute = DefaultLayoutVodRouteImport.update({
  id: '/vod',
  path: '/vod',
  getParentRoute: () => DefaultLayoutRoute,
} as any)
const ApiCafeArticlesRoute = ApiCafeArticlesRouteImport.update({
  id: '/api/cafe-articles',
  path: '/api/cafe-articles',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSoopcommentRoute = ToolsSoopcommentRouteImport.update({
  id: '/tools/soopcomment',
  path: '/tools/soopcomment',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSoopupRoute = ToolsSoopupRouteImport.update({
  id: '/tools/soopup',
  path: '/tools/soopup',
  getParentRoute: () => rootRouteImport,
} as any)
const DefaultLayoutMusicbookIndexRoute =
  DefaultLayoutMusicbookIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DefaultLayoutMusicbookRoute,
  } as any)
const DefaultLayoutMusicbook9mogu9Route =
  DefaultLayoutMusicbook9mogu9RouteImport.update({
    id: '/9mogu9',
    path: '/9mogu9',
    getParentRoute: () => DefaultLayoutMusicbookRoute,
  } as any)
const DefaultLayoutMusicbookHarohaRoute =
  DefaultLayoutMusicbookHarohaRouteImport.update({
    id: '/haroha',
    path: '/haroha',
    getParentRoute: () => DefaultLayoutMusicbookRoute,
  } as any)
const DefaultLayoutMusicbookMarronieRoute =
  DefaultLayoutMusicbookMarronieRouteImport.update({
    id: '/marronie',
    path: '/marronie',
    getParentRoute: () => DefaultLayoutMusicbookRoute,
  } as any)
const DefaultLayoutMusicbookOverlapRoute =
  DefaultLayoutMusicbookOverlapRouteImport.update({
    id: '/overlap',
    path: '/overlap',
    getParentRoute: () => DefaultLayoutMusicbookRoute,
  } as any)
const DefaultLayoutMusicbookYangdokiRoute =
  DefaultLayoutMusicbookYangdokiRouteImport.update({
    id: '/yangdoki',
    path: '/yangdoki',
    getParentRoute: () => DefaultLayoutMusicbookRoute,
  } as any)
const ToolsSoopthumbnailIndexRoute = ToolsSoopthumbnailIndexRouteImport.update({
  id: '/tools/soopthumbnail/',
  path: '/tools/soopthumbnail/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSoopthumbnail9mogu9Route =
  ToolsSoopthumbnail9mogu9RouteImport.update({
    id: '/tools/soopthumbnail/9mogu9',
    path: '/tools/soopthumbnail/9mogu9',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsSoopthumbnailDlsn9911Route =
  ToolsSoopthumbnailDlsn9911RouteImport.update({
    id: '/tools/soopthumbnail/dlsn9911',
    path: '/tools/soopthumbnail/dlsn9911',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsSoopthumbnailHarohaRoute =
  ToolsSoopthumbnailHarohaRouteImport.update({
    id: '/tools/soopthumbnail/haroha',
    path: '/tools/soopthumbnail/haroha',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DefaultLayoutIndexRoute
  '/bluejump-news.xml': typeof BluejumpNewsDotxmlRoute
  '/cafe': typeof DefaultLayoutCafeRoute
  '/calendar': typeof DefaultLayoutCalendarRoute
  '/clipper': typeof DefaultLayoutClipperRoute
  '/live': typeof DefaultLayoutLiveRoute
  '/musicbook': typeof DefaultLayoutMusicbookRouteWithChildren
  '/soop': typeof DefaultLayoutSoopRoute
  '/vod': typeof DefaultLayoutVodRoute
  '/api/cafe-articles': typeof ApiCafeArticlesRoute
  '/tools/soopcomment': typeof ToolsSoopcommentRoute
  '/tools/soopup': typeof ToolsSoopupRoute
  '/musicbook/9mogu9': typeof DefaultLayoutMusicbook9mogu9Route
  '/musicbook/haroha': typeof DefaultLayoutMusicbookHarohaRoute
  '/musicbook/marronie': typeof DefaultLayoutMusicbookMarronieRoute
  '/musicbook/overlap': typeof DefaultLayoutMusicbookOverlapRoute
  '/musicbook/yangdoki': typeof DefaultLayoutMusicbookYangdokiRoute
  '/tools/soopthumbnail/9mogu9': typeof ToolsSoopthumbnail9mogu9Route
  '/tools/soopthumbnail/dlsn9911': typeof ToolsSoopthumbnailDlsn9911Route
  '/tools/soopthumbnail/haroha': typeof ToolsSoopthumbnailHarohaRoute
  '/musicbook/': typeof DefaultLayoutMusicbookIndexRoute
  '/tools/soopthumbnail/': typeof ToolsSoopthumbnailIndexRoute
}
export interface FileRoutesByTo {
  '/bluejump-news.xml': typeof BluejumpNewsDotxmlRoute
  '/cafe': typeof DefaultLayoutCafeRoute
  '/calendar': typeof DefaultLayoutCalendarRoute
  '/clipper': typeof DefaultLayoutClipperRoute
  '/live': typeof DefaultLayoutLiveRoute
  '/soop': typeof DefaultLayoutSoopRoute
  '/vod': typeof DefaultLayoutVodRoute
  '/api/cafe-articles': typeof ApiCafeArticlesRoute
  '/tools/soopcomment': typeof ToolsSoopcommentRoute
  '/tools/soopup': typeof ToolsSoopupRoute
  '/': typeof DefaultLayoutIndexRoute
  '/musicbook/9mogu9': typeof DefaultLayoutMusicbook9mogu9Route
  '/musicbook/haroha': typeof DefaultLayoutMusicbookHarohaRoute
  '/musicbook/marronie': typeof DefaultLayoutMusicbookMarronieRoute
  '/musicbook/overlap': typeof DefaultLayoutMusicbookOverlapRoute
  '/musicbook/yangdoki': typeof DefaultLayoutMusicbookYangdokiRoute
  '/tools/soopthumbnail/9mogu9': typeof ToolsSoopthumbnail9mogu9Route
  '/tools/soopthumbnail/dlsn9911': typeof ToolsSoopthumbnailDlsn9911Route
  '/tools/soopthumbnail/haroha': typeof ToolsSoopthumbnailHarohaRoute
  '/musicbook': typeof DefaultLayoutMusicbookIndexRoute
  '/tools/soopthumbnail': typeof ToolsSoopthumbnailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_defaultLayout': typeof DefaultLayoutRouteWithChildren
  '/bluejump-news.xml': typeof BluejumpNewsDotxmlRoute
  '/_defaultLayout/cafe': typeof DefaultLayoutCafeRoute
  '/_defaultLayout/calendar': typeof DefaultLayoutCalendarRoute
  '/_defaultLayout/clipper': typeof DefaultLayoutClipperRoute
  '/_defaultLayout/live': typeof DefaultLayoutLiveRoute
  '/_defaultLayout/musicbook': typeof DefaultLayoutMusicbookRouteWithChildren
  '/_defaultLayout/soop': typeof DefaultLayoutSoopRoute
  '/_defaultLayout/vod': typeof DefaultLayoutVodRoute
  '/api/cafe-articles': typeof ApiCafeArticlesRoute
  '/tools/soopcomment': typeof ToolsSoopcommentRoute
  '/tools/soopup': typeof ToolsSoopupRoute
  '/_defaultLayout/': typeof DefaultLayoutIndexRoute
  '/_defaultLayout/musicbook/9mogu9': typeof DefaultLayoutMusicbook9mogu9Route
  '/_defaultLayout/musicbook/haroha': typeof DefaultLayoutMusicbookHarohaRoute
  '/_defaultLayout/musicbook/marronie': typeof DefaultLayoutMusicbookMarronieRoute
  '/_defaultLayout/musicbook/overlap': typeof DefaultLayoutMusicbookOverlapRoute
  '/_defaultLayout/musicbook/yangdoki': typeof DefaultLayoutMusicbookYangdokiRoute
  '/tools/soopthumbnail/9mogu9': typeof ToolsSoopthumbnail9mogu9Route
  '/tools/soopthumbnail/dlsn9911': typeof ToolsSoopthumbnailDlsn9911Route
  '/tools/soopthumbnail/haroha': typeof ToolsSoopthumbnailHarohaRoute
  '/_defaultLayout/musicbook/': typeof DefaultLayoutMusicbookIndexRoute
  '/tools/soopthumbnail/': typeof ToolsSoopthumbnailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bluejump-news.xml'
    | '/cafe'
    | '/calendar'
    | '/clipper'
    | '/live'
    | '/musicbook'
    | '/soop'
    | '/vod'
    | '/api/cafe-articles'
    | '/tools/soopcomment'
    | '/tools/soopup'
    | '/musicbook/9mogu9'
    | '/musicbook/haroha'
    | '/musicbook/marronie'
    | '/musicbook/overlap'
    | '/musicbook/yangdoki'
    | '/tools/soopthumbnail/9mogu9'
    | '/tools/soopthumbnail/dlsn9911'
    | '/tools/soopthumbnail/haroha'
    | '/musicbook/'
    | '/tools/soopthumbnail/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bluejump-news.xml'
    | '/cafe'
    | '/calendar'
    | '/clipper'
    | '/live'
    | '/soop'
    | '/vod'
    | '/api/cafe-articles'
    | '/tools/soopcomment'
    | '/tools/soopup'
    | '/'
    | '/musicbook/9mogu9'
    | '/musicbook/haroha'
    | '/musicbook/marronie'
    | '/musicbook/overlap'
    | '/musicbook/yangdoki'
    | '/tools/soopthumbnail/9mogu9'
    | '/tools/soopthumbnail/dlsn9911'
    | '/tools/soopthumbnail/haroha'
    | '/musicbook'
    | '/tools/soopthumbnail'
  id:
    | '__root__'
    | '/_defaultLayout'
    | '/bluejump-news.xml'
    | '/_defaultLayout/cafe'
    | '/_defaultLayout/calendar'
    | '/_defaultLayout/clipper'
    | '/_defaultLayout/live'
    | '/_defaultLayout/musicbook'
    | '/_defaultLayout/soop'
    | '/_defaultLayout/vod'
    | '/api/cafe-articles'
    | '/tools/soopcomment'
    | '/tools/soopup'
    | '/_defaultLayout/'
    | '/_defaultLayout/musicbook/9mogu9'
    | '/_defaultLayout/musicbook/haroha'
    | '/_defaultLayout/musicbook/marronie'
    | '/_defaultLayout/musicbook/overlap'
    | '/_defaultLayout/musicbook/yangdoki'
    | '/tools/soopthumbnail/9mogu9'
    | '/tools/soopthumbnail/dlsn9911'
    | '/tools/soopthumbnail/haroha'
    | '/_defaultLayout/musicbook/'
    | '/tools/soopthumbnail/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DefaultLayoutRoute: typeof DefaultLayoutRouteWithChildren
  BluejumpNewsDotxmlRoute: typeof BluejumpNewsDotxmlRoute
  ApiCafeArticlesRoute: typeof ApiCafeArticlesRoute
  ToolsSoopcommentRoute: typeof ToolsSoopcommentRoute
  ToolsSoopupRoute: typeof ToolsSoopupRoute
  ToolsSoopthumbnail9mogu9Route: typeof ToolsSoopthumbnail9mogu9Route
  ToolsSoopthumbnailDlsn9911Route: typeof ToolsSoopthumbnailDlsn9911Route
  ToolsSoopthumbnailHarohaRoute: typeof ToolsSoopthumbnailHarohaRoute
  ToolsSoopthumbnailIndexRoute: typeof ToolsSoopthumbnailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_defaultLayout': {
      id: '/_defaultLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bluejump-news.xml': {
      id: '/bluejump-news.xml'
      path: '/bluejump-news.xml'
      fullPath: '/bluejump-news.xml'
      preLoaderRoute: typeof BluejumpNewsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_defaultLayout/': {
      id: '/_defaultLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutIndexRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/cafe': {
      id: '/_defaultLayout/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof DefaultLayoutCafeRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/calendar': {
      id: '/_defaultLayout/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof DefaultLayoutCalendarRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/clipper': {
      id: '/_defaultLayout/clipper'
      path: '/clipper'
      fullPath: '/clipper'
      preLoaderRoute: typeof DefaultLayoutClipperRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/live': {
      id: '/_defaultLayout/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof DefaultLayoutLiveRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/musicbook': {
      id: '/_defaultLayout/musicbook'
      path: '/musicbook'
      fullPath: '/musicbook'
      preLoaderRoute: typeof DefaultLayoutMusicbookRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/soop': {
      id: '/_defaultLayout/soop'
      path: '/soop'
      fullPath: '/soop'
      preLoaderRoute: typeof DefaultLayoutSoopRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/_defaultLayout/vod': {
      id: '/_defaultLayout/vod'
      path: '/vod'
      fullPath: '/vod'
      preLoaderRoute: typeof DefaultLayoutVodRouteImport
      parentRoute: typeof DefaultLayoutRoute
    }
    '/api/cafe-articles': {
      id: '/api/cafe-articles'
      path: '/api/cafe-articles'
      fullPath: '/api/cafe-articles'
      preLoaderRoute: typeof ApiCafeArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/soopcomment': {
      id: '/tools/soopcomment'
      path: '/tools/soopcomment'
      fullPath: '/tools/soopcomment'
      preLoaderRoute: typeof ToolsSoopcommentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/soopup': {
      id: '/tools/soopup'
      path: '/tools/soopup'
      fullPath: '/tools/soopup'
      preLoaderRoute: typeof ToolsSoopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_defaultLayout/musicbook/': {
      id: '/_defaultLayout/musicbook/'
      path: '/'
      fullPath: '/musicbook/'
      preLoaderRoute: typeof DefaultLayoutMusicbookIndexRouteImport
      parentRoute: typeof DefaultLayoutMusicbookRoute
    }
    '/_defaultLayout/musicbook/9mogu9': {
      id: '/_defaultLayout/musicbook/9mogu9'
      path: '/9mogu9'
      fullPath: '/musicbook/9mogu9'
      preLoaderRoute: typeof DefaultLayoutMusicbook9mogu9RouteImport
      parentRoute: typeof DefaultLayoutMusicbookRoute
    }
    '/_defaultLayout/musicbook/haroha': {
      id: '/_defaultLayout/musicbook/haroha'
      path: '/haroha'
      fullPath: '/musicbook/haroha'
      preLoaderRoute: typeof DefaultLayoutMusicbookHarohaRouteImport
      parentRoute: typeof DefaultLayoutMusicbookRoute
    }
    '/_defaultLayout/musicbook/marronie': {
      id: '/_defaultLayout/musicbook/marronie'
      path: '/marronie'
      fullPath: '/musicbook/marronie'
      preLoaderRoute: typeof DefaultLayoutMusicbookMarronieRouteImport
      parentRoute: typeof DefaultLayoutMusicbookRoute
    }
    '/_defaultLayout/musicbook/overlap': {
      id: '/_defaultLayout/musicbook/overlap'
      path: '/overlap'
      fullPath: '/musicbook/overlap'
      preLoaderRoute: typeof DefaultLayoutMusicbookOverlapRouteImport
      parentRoute: typeof DefaultLayoutMusicbookRoute
    }
    '/_defaultLayout/musicbook/yangdoki': {
      id: '/_defaultLayout/musicbook/yangdoki'
      path: '/yangdoki'
      fullPath: '/musicbook/yangdoki'
      preLoaderRoute: typeof DefaultLayoutMusicbookYangdokiRouteImport
      parentRoute: typeof DefaultLayoutMusicbookRoute
    }
    '/tools/soopthumbnail/': {
      id: '/tools/soopthumbnail/'
      path: '/tools/soopthumbnail'
      fullPath: '/tools/soopthumbnail/'
      preLoaderRoute: typeof ToolsSoopthumbnailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/soopthumbnail/9mogu9': {
      id: '/tools/soopthumbnail/9mogu9'
      path: '/tools/soopthumbnail/9mogu9'
      fullPath: '/tools/soopthumbnail/9mogu9'
      preLoaderRoute: typeof ToolsSoopthumbnail9mogu9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/soopthumbnail/dlsn9911': {
      id: '/tools/soopthumbnail/dlsn9911'
      path: '/tools/soopthumbnail/dlsn9911'
      fullPath: '/tools/soopthumbnail/dlsn9911'
      preLoaderRoute: typeof ToolsSoopthumbnailDlsn9911RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/soopthumbnail/haroha': {
      id: '/tools/soopthumbnail/haroha'
      path: '/tools/soopthumbnail/haroha'
      fullPath: '/tools/soopthumbnail/haroha'
      preLoaderRoute: typeof ToolsSoopthumbnailHarohaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DefaultLayoutMusicbookRouteChildren {
  DefaultLayoutMusicbook9mogu9Route: typeof DefaultLayoutMusicbook9mogu9Route
  DefaultLayoutMusicbookHarohaRoute: typeof DefaultLayoutMusicbookHarohaRoute
  DefaultLayoutMusicbookMarronieRoute: typeof DefaultLayoutMusicbookMarronieRoute
  DefaultLayoutMusicbookOverlapRoute: typeof DefaultLayoutMusicbookOverlapRoute
  DefaultLayoutMusicbookYangdokiRoute: typeof DefaultLayoutMusicbookYangdokiRoute
  DefaultLayoutMusicbookIndexRoute: typeof DefaultLayoutMusicbookIndexRoute
}

const DefaultLayoutMusicbookRouteChildren: DefaultLayoutMusicbookRouteChildren =
  {
    DefaultLayoutMusicbook9mogu9Route: DefaultLayoutMusicbook9mogu9Route,
    DefaultLayoutMusicbookHarohaRoute: DefaultLayoutMusicbookHarohaRoute,
    DefaultLayoutMusicbookMarronieRoute: DefaultLayoutMusicbookMarronieRoute,
    DefaultLayoutMusicbookOverlapRoute: DefaultLayoutMusicbookOverlapRoute,
    DefaultLayoutMusicbookYangdokiRoute: DefaultLayoutMusicbookYangdokiRoute,
    DefaultLayoutMusicbookIndexRoute: DefaultLayoutMusicbookIndexRoute,
  }

const DefaultLayoutMusicbookRouteWithChildren =
  DefaultLayoutMusicbookRoute._addFileChildren(
    DefaultLayoutMusicbookRouteChildren,
  )

interface DefaultLayoutRouteChildren {
  DefaultLayoutCafeRoute: typeof DefaultLayoutCafeRoute
  DefaultLayoutCalendarRoute: typeof DefaultLayoutCalendarRoute
  DefaultLayoutClipperRoute: typeof DefaultLayoutClipperRoute
  DefaultLayoutLiveRoute: typeof DefaultLayoutLiveRoute
  DefaultLayoutMusicbookRoute: typeof DefaultLayoutMusicbookRouteWithChildren
  DefaultLayoutSoopRoute: typeof DefaultLayoutSoopRoute
  DefaultLayoutVodRoute: typeof DefaultLayoutVodRoute
  DefaultLayoutIndexRoute: typeof DefaultLayoutIndexRoute
}

const DefaultLayoutRouteChildren: DefaultLayoutRouteChildren = {
  DefaultLayoutCafeRoute: DefaultLayoutCafeRoute,
  DefaultLayoutCalendarRoute: DefaultLayoutCalendarRoute,
  DefaultLayoutClipperRoute: DefaultLayoutClipperRoute,
  DefaultLayoutLiveRoute: DefaultLayoutLiveRoute,
  DefaultLayoutMusicbookRoute: DefaultLayoutMusicbookRouteWithChildren,
  DefaultLayoutSoopRoute: DefaultLayoutSoopRoute,
  DefaultLayoutVodRoute: DefaultLayoutVodRoute,
  DefaultLayoutIndexRoute: DefaultLayoutIndexRoute,
}

const DefaultLayoutRouteWithChildren = DefaultLayoutRoute._addFileChildren(
  DefaultLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DefaultLayoutRoute: DefaultLayoutRouteWithChildren,
  BluejumpNewsDotxmlRoute: BluejumpNewsDotxmlRoute,
  ApiCafeArticlesRoute: ApiCafeArticlesRoute,
  ToolsSoopcommentRoute: ToolsSoopcommentRoute,
  ToolsSoopupRoute: ToolsSoopupRoute,
  ToolsSoopthumbnail9mogu9Route: ToolsSoopthumbnail9mogu9Route,
  ToolsSoopthumbnailDlsn9911Route: ToolsSoopthumbnailDlsn9911Route,
  ToolsSoopthumbnailHarohaRoute: ToolsSoopthumbnailHarohaRoute,
  ToolsSoopthumbnailIndexRoute: ToolsSoopthumbnailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
